START_POSITION = (77, 235)
LEFT_DOOR_POSITION = (24, 235)
RIGHT_DOOR_POSITION = (130, 235)
BOTTOM_RIGHT_POSITION = (123, 148)
TOP_RIGHT_LADDER_POSITION = (132, 192)
BOTTOM_MID_LADDER_POSITION = (77, 192)

ALL_GOAL_POSITIONS = [
    START_POSITION,
    LEFT_DOOR_POSITION,
    RIGHT_DOOR_POSITION,
    BOTTOM_RIGHT_POSITION,
    TOP_RIGHT_LADDER_POSITION,
    BOTTOM_MID_LADDER_POSITION
]

START_FILE = "start_states.pkl"
LEFT_DOOR_FILE = "left_door_goal.pkl"
RIGHT_DOOR_FILE = "right_door_goal.pkl"
BOTTOM_RIGHT_FILE = "bottom_right_states.pkl"
TOP_RIGHT_LADDER_FILE = "top_bottom_right_ladder_states.pkl"
BOTTOM_MID_LADDER_FILE = "bottom_mid_ladder_goal.pkl"

ALL_GOAL_FILES = [
    START_FILE,
    LEFT_DOOR_FILE,
    RIGHT_DOOR_FILE,
    BOTTOM_RIGHT_FILE,
    TOP_RIGHT_LADDER_FILE,
    BOTTOM_MID_LADDER_FILE
]
